# What is a Tensor?

A tensor is a multi-dimensional array that is a fundamental building block in PyTorch (and other machine learning libraries like TensorFlow). Tensors are similar to NumPy arrays, but they come with additional capabilities, particularly for GPU acceleration, which makes them powerful for deep learning tasks.

## Key Points about Tensors:

### Multi-dimensional Arrays:

Tensors can have zero or more dimensions. For example:
- A scalar (single number) is a 0-dimensional tensor.
- A vector (1D array) is a 1-dimensional tensor.
- A matrix (2D array) is a 2-dimensional tensor.
- Higher-dimensional tensors (3D, 4D, etc.) can be used to represent more complex data.

### Data Types:

Tensors can hold various types of data, such as floats, integers, and more. The most common data type for deep learning tasks is a floating-point number (float32).

### Device Support:

Tensors can be moved to and processed on different devices, such as CPUs or GPUs. This allows for efficient computations in deep learning.

## Creating Tensors:

Here are some examples of how to create and manipulate tensors in PyTorch:

### Import PyTorch:

In [1]:
import torch

### Creating Tensors:

#### From a list:

In [2]:
tensor_from_list = torch.tensor([1, 2, 3])
print(tensor_from_list)

tensor([1, 2, 3])


#### Random tensor:

In [3]:
random_tensor = torch.rand(2, 3)
print(random_tensor)

tensor([[0.4447, 0.3214, 0.6253],
        [0.1357, 0.6016, 0.4085]])


#### Tensor filled with zeros:

In [4]:
zeros_tensor = torch.zeros(2, 3)
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Tensor filled with ones:

In [5]:
ones_tensor = torch.ones(2, 3)
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Tensor Properties:

#### Shape: The dimensions of the tensor.

In [6]:
print(tensor_from_list.shape)

torch.Size([3])


#### Data Type: The type of data stored in the tensor.

In [7]:
print(tensor_from_list.dtype)

torch.int64


### Basic Tensor Operations:

#### Addition:

In [8]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = a + b
print(result)

tensor([5, 7, 9])


#### Matrix multiplication:

In [9]:
d = torch.rand(2, 3)
e = torch.rand(3, 2)
matrix_result = torch.matmul(d, e)
print(d)
print(e)
print(matrix_result)

tensor([[0.2972, 0.4080],
        [0.4839, 0.6842]])


## Example Code

Here's a simple example demonstrating the creation and manipulation of tensors:

In [11]:
import torch

# Create a tensor from a list
tensor_from_list = torch.tensor([1, 2, 3])
print('Tensor from list:', tensor_from_list)

# Create a random tensor
random_tensor = torch.rand(2, 3)
print('Random tensor:', random_tensor)

# Create a tensor filled with zeros
zeros_tensor = torch.zeros(2, 3)
print('Zeros tensor:', zeros_tensor)

# Tensor properties
print('Shape of tensor_from_list:', tensor_from_list.shape)
print('Data type of tensor_from_list:', tensor_from_list.dtype)

# Basic tensor operations
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = a + b
print('Addition result:', result)

d = torch.rand(2, 3)
e = torch.rand(3, 2)
matrix_result = torch.matmul(d, e)
print('Matrix multiplication result:', matrix_result)

Tensor from list: tensor([1, 2, 3])
Random tensor: tensor([[0.3704, 0.5043, 0.6367],
        [0.6332, 0.2454, 0.5430]])
Zeros tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Shape of tensor_from_list: torch.Size([3])
Data type of tensor_from_list: torch.int64
Addition result: tensor([5, 7, 9])
Matrix multiplication result: tensor([[1.0407, 0.1639],
        [0.9820, 0.5061]])


In [19]:
tensor = torch.randint(low=0, high =10, size=(10,10))
tensor

tensor([[9, 4, 6, 9, 8, 9, 5, 3, 8, 4],
        [7, 7, 5, 1, 7, 2, 3, 2, 8, 0],
        [0, 6, 8, 9, 7, 5, 4, 2, 6, 7],
        [7, 0, 2, 2, 2, 4, 0, 2, 3, 2],
        [7, 0, 0, 2, 2, 7, 9, 1, 6, 5],
        [3, 2, 0, 2, 6, 0, 1, 2, 3, 6],
        [7, 1, 3, 4, 6, 0, 9, 6, 2, 2],
        [4, 0, 6, 7, 2, 1, 1, 9, 1, 5],
        [3, 9, 2, 8, 3, 7, 8, 7, 5, 1],
        [7, 0, 9, 2, 3, 4, 7, 1, 1, 4]])

In [18]:
# Function to count occurrences in each row and column
def count_occurrences(tensor):
    row_counts = []
    col_counts = []
    
    # Count occurrences in each row
    for row in tensor:
        unique, counts = torch.unique(row, return_counts=True)
        row_counts.append(dict(zip(unique.tolist(), counts.tolist())))
    
    # Count occurrences in each column
    for col in tensor.T:  # Transpose to iterate over columns
        unique, counts = torch.unique(col, return_counts=True)
        col_counts.append(dict(zip(unique.tolist(), counts.tolist())))
    
    return row_counts, col_counts

In [20]:
# Get the counts
row_counts, col_counts = count_occurrences(tensor)

In [21]:
row_counts

[{3: 1, 4: 2, 5: 1, 6: 1, 8: 2, 9: 3},
 {0: 1, 1: 1, 2: 2, 3: 1, 5: 1, 7: 3, 8: 1},
 {0: 1, 2: 1, 4: 1, 5: 1, 6: 2, 7: 2, 8: 1, 9: 1},
 {0: 2, 2: 5, 3: 1, 4: 1, 7: 1},
 {0: 2, 1: 1, 2: 2, 5: 1, 6: 1, 7: 2, 9: 1},
 {0: 2, 1: 1, 2: 3, 3: 2, 6: 2},
 {0: 1, 1: 1, 2: 2, 3: 1, 4: 1, 6: 2, 7: 1, 9: 1},
 {0: 1, 1: 3, 2: 1, 4: 1, 5: 1, 6: 1, 7: 1, 9: 1},
 {1: 1, 2: 1, 3: 2, 5: 1, 7: 2, 8: 2, 9: 1},
 {0: 1, 1: 2, 2: 1, 3: 1, 4: 2, 7: 2, 9: 1}]

In [22]:
col_counts

[{0: 1, 3: 2, 4: 1, 7: 5, 9: 1},
 {0: 4, 1: 1, 2: 1, 4: 1, 6: 1, 7: 1, 9: 1},
 {0: 2, 2: 2, 3: 1, 5: 1, 6: 2, 8: 1, 9: 1},
 {1: 1, 2: 4, 4: 1, 7: 1, 8: 1, 9: 2},
 {2: 3, 3: 2, 6: 2, 7: 2, 8: 1},
 {0: 2, 1: 1, 2: 1, 4: 2, 5: 1, 7: 2, 9: 1},
 {0: 1, 1: 2, 3: 1, 4: 1, 5: 1, 7: 1, 8: 1, 9: 2},
 {1: 2, 2: 4, 3: 1, 6: 1, 7: 1, 9: 1},
 {1: 2, 2: 1, 3: 2, 5: 1, 6: 2, 8: 2},
 {0: 1, 1: 1, 2: 2, 4: 2, 5: 2, 6: 1, 7: 1}]