In [1]:
# !pip install scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 28.6 MB/s eta 0:00:00m eta 0:00:010:0101


In [19]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler

In [6]:
wine_data = load_wine()
wine_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [7]:
X, y = wine_data["data"], wine_data["target"]

In [9]:
X, y

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [11]:
scalar = StandardScaler()
X_scalar = scalar.fit_transform(X)
X_scalar

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [46]:
class WineDataset(Dataset):
    def __init__(self, features, labels):
        self.features = torch.tensor(features, dtype = torch.float32)
        self.labels = torch.tensor(labels, dtype = torch.long)
        
    def __len__(self):
        return len(self.features)
    
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]
    
    
wine_dataset = WineDataset(X_scalar, y)

In [47]:
trainloader = DataLoader(wine_dataset, batch_size=32, shuffle=True)

for features, labels in trainloader:
    print(features.shape)
    print(labels.shape)

torch.Size([32, 13])
torch.Size([32])
torch.Size([32, 13])
torch.Size([32])
torch.Size([32, 13])
torch.Size([32])
torch.Size([32, 13])
torch.Size([32])
torch.Size([32, 13])
torch.Size([32])
torch.Size([18, 13])
torch.Size([18])


In [48]:
class NeuralNet(nn.Module):
    def __init__(self):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(13, 40)
        self.fc2 = nn.Linear(40, 20)
        self.fc3 = nn.Linear(20, 3)
    
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
neural_net = NeuralNet()
neural_net

NeuralNet(
  (fc1): Linear(in_features=13, out_features=40, bias=True)
  (fc2): Linear(in_features=40, out_features=20, bias=True)
  (fc3): Linear(in_features=20, out_features=3, bias=True)
)

# lr (Learning Rate)
Definition: The learning rate (lr) is a scalar that determines the step size at each iteration while moving toward a minimum of the loss function.
Purpose: It controls how much to change the model in response to the estimated error each time the model weights are updated.
Effect:
High Learning Rate: Can lead to faster convergence, but may overshoot the optimal solution, causing the training process to become unstable.
Low Learning Rate: Leads to more stable convergence but requires more iterations to reach the minimum of the loss function, potentially resulting in a longer training time.
# momentum
Definition: Momentum is a technique that helps accelerate gradients vectors in the right directions, thus leading to faster converging.
Purpose: It helps to dampen oscillations in the optimization process and can speed up training by gaining momentum in directions that have consistent gradients.
Effect:
High Momentum: Can help to overcome local minima and accelerate convergence, but if too high, it might overshoot or lead to instability.
Low Momentum: Makes the optimizer behave more like standard gradient descent, which can be slower and more prone to getting stuck in local minima.

In [55]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(neural_net.parameters(), lr=0.001, weight_decay=0.01)
# optimizer = optim.AdamW(neural_net.parameters(), lr=0.001, betas=(0.9, 0.999), eps=1e-8, weight_decay=0.01)
# optimizer = optim.SGD(neural_net.parameters(), lr=0.01, momentum=0.9)

In [56]:
for epoch in range(10):
    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        
        optimizer.zero_grad()
        
        outputs = neural_net(inputs)
        print(output)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
        if i % 5 == 0:  # print every 10 mini-batches
            print(f'Epoch {epoch + 1}, Batch {i + 1}, Loss: {running_loss / 10:.3f}')
            running_loss = 0.0

Linear(in_features=20, out_features=3, bias=True)
Epoch 1, Batch 1, Loss: 0.001
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Epoch 1, Batch 6, Loss: 0.016
Linear(in_features=20, out_features=3, bias=True)
Epoch 2, Batch 1, Loss: 0.004
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Epoch 2, Batch 6, Loss: 0.010
Linear(in_features=20, out_features=3, bias=True)
Epoch 3, Batch 1, Loss: 0.004
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)
Linear(in_features=20, out_features=3, bias=True)


In [57]:
correct = 0
total = 0
with torch.no_grad():
    for data in trainloader:
        inputs, labels = data
        outputs = neural_net(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy of the network on the training set: {100 * correct / total:.2f}%')


Accuracy of the network on the training set: 100.00%
